### ISSUE TITLE
ReqHex fails in :zlib for non-200 codes

### ISSUE THREAD

**Issue by karol-t-wilk** [wojtekmach/req_hex#3]
Tested on the `/packages/name` endpoint. When given a nonexistent package to fetch, `:zlib` raises `:data_error`.

```elixir
Req.new([url: "https://repo.hex.pm/packages/nope"])
|> ReqHex.attach()
|> Req.request!()
```
Outputs:
```
** (ErlangError) Erlang error: :data_error
    :zlib.inflate_nif(#Reference<0.1985853986.1523187715.160087>, 8192, 16384, 0)
    :zlib.dequeue_all_chunks_1/3
    :zlib.inflate/3
    :zlib.gunzip/1
    (hex_core 0.8.4) /home/kwilk/.cache/mix/installs/elixir-1.16.3-erts-14.2.5/fbff4fb7875ecf6d75bb039cf0617905/deps/hex_core/src/hex_registry.erl:103: :hex_registry.unpack_package/4
    (req_hex 0.1.1) lib/req_hex.ex:78: ReqHex.decode_package/2
    (elixir 1.16.3) lib/map.ex:916: Map.update!/3
    #cell:oe5qnrad2dzvy3zd:3: (file)
```

Without the plugin, Req just returns the error xml as plaintext:

```elixir
Req.new([url: "https://repo.hex.pm/packages/nope"])
|> Req.request!()
```

```
#Req.Response<
  status: 404,
  headers: %{
    "accept-ranges" => ["bytes"],
    "age" => ["0"],
    "connection" => ["keep-alive"],
    "content-type" => ["application/xml"],
    "date" => ["Fri, 14 Jun 2024 06:47:34 GMT"],
    "server" => ["AmazonS3"],
    "transfer-encoding" => ["chunked"],
    "via" => ["1.1 varnish"],
    "x-amz-id-2" => ["OHmFSdlpCO5t5YMhrz3jajCK5cfdK5kVKUj6sS+zpnt/ovCGU3xhGGvPjd+R/ZmC7b4TkPxLS8s="],
    "x-amz-request-id" => ["QZAA61B7ZBKZM2SJ"],
    "x-cache" => ["MISS"],
    "x-cache-hits" => ["0"],
    "x-served-by" => ["cache-ams2100144-AMS"],
    "x-timer" => ["S1718347654.070074,VS0,VE385"]
  },
  body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>QZAA61B7ZBKZM2SJ</RequestId><HostId>OHmFSdlpCO5t5YMhrz3jajCK5cfdK5kVKUj6sS+zpnt/ovCGU3xhGGvPjd+R/ZmC7b4TkPxLS8s=</HostId></Error>",
  trailers: %{},
  private: %{},
  ...
>
```

Tested on Req 0.4.14, ReqHex 0.1.1, Elixir 1.16.3, OTP 26.2.5

**Comment by wojtekmach** [comment]
Thanks for the report. This is pretty embarrassing, fixed in dc483405532cc4f0326f7d6d2f9f0e482623b89e!
